name: crates

on:
  release:
    types: [published]

jobs:

  crates:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Toolchain
      uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

    - name: Publish
      uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --token {{ "${{ secrets.CARGO_API_KEY " }}}} --allow-dirty