name: Building

on:
  push:
    branches: master

jobs:
  build:
    name: Target ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: # rustup target list
          - linux-x86_64-gnu
          - linux-armv7-gnu
          - macos-x86_64
          - windows-x86_64-msvc
        include:
          - name: linux-x86_64-gnu
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - name: linux-armv7-gnu
            os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
          - name: macos-x86_64
            os: macos-latest
            target: x86_64-apple-darwin
          - name: windows-x86_64-msvc
            os: windows-latest
            target: x86_64-pc-windows-msvc
          # - name: windows-x86_64-gnu
          #   os: windows-latest
          #   target: x86_64-pc-windows-gnu

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Toolchain
        uses: actions-rs/toolchain@v1
        with:
          # profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}

      # - name: Show
      #   run: tree target

      # - name: Show Linux
      #   if: ${{ matrix.name != "windows-x86_64-msvc" }}
      #   run: find target

      # - name: Show Windows
      #   if: ${{ matrix.name == "windows-x86_64-msvc" }}
      #   run: dir target\*\

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.target }}/release-rust
          asset_name: ${{ matrix.name }}
          tag: ${{ github.ref }}
