name: Docker

env:
  project: 'release-rust'

on:
  push:
    branches: master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      # # - name: Login to DockerHub
      # #   uses: docker/login-action@v1
      # #   with:
      # #     username: ${{ secrets.DOCKER_USERNAME }}
      # #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build
      #   id: build
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: false
      #     tags: tcurdt/${{ env.project }}:latest
      #     platforms: linux/amd64
      #     # platforms: linux/386,linux/amd64,linux/arm64,linux/arm/v7
      #     # secrets: |
      #     #   GIT_AUTH_TOKEN=${{ github.token }}

      # - name: Digest
      #   run: echo ${{ steps.build.outputs.digest }}
