name: crates

on:
  release:
    types: [ published ]

jobs:

  crates:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

    - name: Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Publish
      uses: actions-rs/cargo@v1
      with:
        command: publish
        args: --token "${{ secrets.CRATES_TOKEN }}" --allow-dirty